"""Write the generated Markdown from _variables.yml.

Outputs (all overwritten on every run, never edited by hand):
  _includes/facts.md         the counts under the landing page's hero
  _includes/days.md          the days as cards
  _includes/path.md          the module arc on the landing page
  _includes/schedule.md      the timetable: one grid for each run of days on the same clock
  _includes/module-shape.md  one paragraph: how long a module is on each clock
  _includes/welcome-days.md  the welcome deck's five-days slide
  _includes/welcome-clocks.md  the welcome deck's timetable slide: one column per clock
  _includes/welcome-data.md  the welcome deck's datasets slide
  _includes/day-N.md         the module cards for one day
  _includes/module-NN.md     the header block of one module page
  _includes/notebooks.md     the notebook index with Colab links
  _includes/readiness.md     the readiness page: evidence per module, blocking work
  _includes/readiness-summary.md  the one-paragraph status on the landing, FAQ and teach pages
  _includes/sidebar.yml      the module sidebar, read by _quarto.yml (metadata-files)
  README.md                  the regions between the BEGIN/END status, modules and days markers

It also creates a stub module page for any module that has none. Existing
module pages are never touched.

The readiness outputs read modules.mNN.readiness and readiness: in _variables.yml and the
run records in runs/ (scripts/readiness.py). They print dates from the records, never today's
date, so they change only when the repository does.

Each day runs on a named clock (schedule.clocks). The clock's module units take the
day's `slots` in order (placements()). A unit is one `module` slot, or a `part: briefing`
slot with the `part: lab` slot after it, so a module can span lunch. A module that fills
one unit has the clock's briefing/lab/debrief shape; one that fills several (the
capstone) is shown as hands-on.

Module numbers start at 0. Module 0 is pre-work (`day: 0`) with `notebook: false`: it
gets a module page, a pre-work step on the landing path and in the sidebar, and a
README row, but no module slot and no row in the notebook index. A day's optional
`clinic` (drop-in help with Module 0) fills its clock's `clinic` slot.

Run:  uv run --group site python scripts/gen_tables.py
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lab_steps  # noqa: E402
import learner_pages  # noqa: E402
import live_plan  # noqa: E402
import readiness  # noqa: E402
import run_records  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
INCLUDES = ROOT / "_includes"
NOTICE = "<!-- GENERATED by scripts/gen_tables.py from _variables.yml. Do not edit by hand. -->"
# The live plan and pace rows come from a briefing's front matter, not _variables.yml.
LIVE_NOTICE = (
    "<!-- GENERATED by scripts/gen_tables.py from the `live:` front matter of"
    " modules/{slug}.qmd. Do not edit by hand. -->"
)
GLOSSARY_NOTICE = (
    "<!-- GENERATED by scripts/gen_tables.py from _glossary.yml. Do not edit by hand. -->"
)
WORKSHEET_NOTICE = (
    "<!-- GENERATED by scripts/gen_tables.py from _worksheet.yml. Do not edit by hand. -->"
)
YAML_NOTICE = "# GENERATED by scripts/gen_tables.py from _variables.yml. Do not edit by hand."
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"
NO_NOTEBOOK = "No notebook: runs in your terminal"
PREWORK = "Before Day 1 · Pre-Work"


def load_variables() -> dict:
    return yaml.safe_load((ROOT / "_variables.yml").read_text(encoding="utf-8"))


def modules_in_order(v: dict) -> list[tuple[str, dict]]:
    return sorted(v["modules"].items(), key=lambda kv: kv[1]["n"])


def days_in_order(v: dict) -> list[dict]:
    return sorted(v["days"].values(), key=lambda d: d["n"])


def notebook_exists(slug: str) -> bool:
    return (ROOT / "notebooks" / f"{slug}.ipynb").exists()


def has_notebook(m: dict) -> bool:
    return m.get("notebook", True)


def colab_badge(v: dict, slug: str) -> str:
    """A Colab badge if the notebook exists, otherwise a plain note."""
    if not notebook_exists(slug):
        return "In preparation"
    return f"[![Open in Colab]({BADGE})]({v['repo']['colab_base']}/{slug}.ipynb)"


def lab_cell(v: dict, m: dict) -> str:
    return colab_badge(v, m["slug"]) if has_notebook(m) else NO_NOTEBOOK


def slot_parts(slot) -> tuple[str, str | None]:
    """A day slot is a module key, or {module, label} to override the label."""
    if isinstance(slot, dict):
        return slot["module"], slot.get("label")
    return slot, None


def write(path: Path, body: str, notice: str = NOTICE) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{notice}\n\n{body.rstrip()}\n", encoding="utf-8")


def clock(minutes: int) -> str:
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


def to_minutes(hhmm: str) -> int:
    return int(hhmm[:2]) * 60 + int(hhmm[3:])


def span(slot: dict) -> int:
    """A slot's length in minutes."""
    return to_minutes(slot["end"]) - to_minutes(slot["start"])


def clock_of(v: dict, day: dict) -> dict:
    return v["schedule"]["clocks"][day["clock"]]


def units(clk: dict) -> list[list[dict]]:
    """The clock's module units, in order. A unit is one `module` slot, or a
    `part: briefing` slot together with the `part: lab` slot that follows it."""
    out, pending = [], None
    for s in clk["slots"]:
        if s["kind"] != "module":
            continue
        part = s.get("part")
        if part is None and pending is None:
            out.append([s])
        elif part == "briefing" and pending is None:
            pending = [s]
        elif part == "lab" and pending is not None:
            out.append(pending + [s])
            pending = None
        else:
            raise ValueError(f"slot {s['start']}: `part: lab` must close a `part: briefing` slot")
    if pending is not None:
        raise ValueError(f"slot {pending[0]['start']}: `part: briefing` with no `part: lab`")
    return out


def placements(v: dict, day: dict) -> list[dict]:
    """The day's `slots` matched to its clock's units, in order: one dict per unit
    with the module `key`, its `label` (or None) and the unit's clock `slots`."""
    return [
        {"key": key, "label": label, "slots": unit}
        for (key, label), unit in zip(
            (slot_parts(s) for s in day["slots"]), units(clock_of(v, day)), strict=True
        )
    ]


def module_placements(v: dict, key: str) -> list[tuple[dict, dict]]:
    """(day, placement) for each unit that module `key` fills. Empty for pre-work."""
    return [(d, p) for d in days_in_order(v) for p in placements(v, d) if p["key"] == key]


def minutes_of(v: dict, key: str) -> int:
    """The minutes the clocks give module `key` (0 for pre-work)."""
    return sum(span(s) for _, p in module_placements(v, key) for s in p["slots"])


def shape(v: dict, key: str) -> dict | None:
    """{briefing, lab[, debrief]} minutes for a module that fills exactly one unit.
    None for pre-work and for a module that fills several (the capstone is hands-on)."""
    found = module_placements(v, key)
    return clock_of(v, found[0][0])["shape"] if len(found) == 1 else None


def is_prework(m: dict) -> bool:
    return m["day"] == 0


def prework(v: dict) -> list[tuple[str, dict]]:
    return [(key, m) for key, m in modules_in_order(v) if is_prework(m)]


def clinic_of(v: dict, key: str) -> tuple[dict, dict] | None:
    """(day, slot) if module `key` fills a day's optional clinic slot."""
    for d in days_in_order(v):
        if d.get("clinic") and slot_parts(d["clinic"])[0] == key:
            return d, next(s for s in clock_of(v, d)["slots"] if s["kind"] == "clinic")
    return None


def module_clock(v: dict, key: str) -> str:
    """'09:10–10:45', or one range per stretch of a module that spans a break:
    '11:30–12:25 · 13:25–14:30'. Pre-work gives its clinic's time."""
    ranges: list[list[str]] = []
    for _, p in module_placements(v, key):
        for s in p["slots"]:
            if ranges and ranges[-1][1] == s["start"]:
                ranges[-1][1] = s["end"]
            else:
                ranges.append([s["start"], s["end"]])
    if not ranges:
        found = clinic_of(v, key)
        return f"{found[1]['start']}–{found[1]['end']}" if found else ""
    return " · ".join(f"{a}–{b}" for a, b in ranges)


def shape_text(s: dict) -> str:
    """'45 briefing, 50 lab' or '55 briefing, 55 lab, 10 debrief'."""
    return ", ".join(f"{minutes} {part}" for part, minutes in s.items())


def timing(v: dict, key: str, m: dict) -> str:
    """'120 minutes (55 briefing, 55 lab, 10 debrief)'. Also used for notebook headers."""
    if is_prework(m):
        found = clinic_of(v, key)
        if not found:
            return f"{m['minutes']} minutes, pre-work"
        clinic = f"optional clinic on Day {found[0]['n']}, {module_clock(v, key)}"
        return f"{m['minutes']} minutes, pre-work; {clinic}"
    s = shape(v, key)
    if s:
        return f"{m['minutes']} minutes ({shape_text(s)})"
    return f"{m['minutes']} minutes"


def colab_button(v: dict, m: dict, text: str = "Open in Colab") -> str:
    """A styled link to the lab (site pages only; README keeps the image badge)."""
    if not has_notebook(m):
        return f"[{NO_NOTEBOOK}]{{.lab-note}}"
    if not notebook_exists(m["slug"]):
        return "[Lab in preparation]{.lab-note}"
    return f"[{text}]({v['repo']['colab_base']}/{m['slug']}.ipynb){{.btn-colab}}"


def chips(items: list[str]) -> str:
    return " ".join(f"[{item}]{{.chip}}" for item in items)


def day_modules(v: dict, day: dict) -> list[tuple[str, dict]]:
    """The day's modules in order, each once (the capstone fills two units)."""
    keys = list(dict.fromkeys(p["key"] for p in placements(v, day)))
    return [(key, v["modules"][key]) for key in keys]


def clock_groups(v: dict) -> list[tuple[str, list[dict]]]:
    """The days on each clock, in order of first use: [(clock name, [day, ...]), ...].
    Days on one clock share one timetable grid even when they are not consecutive."""
    groups: dict[str, list[dict]] = {}
    for d in days_in_order(v):
        groups.setdefault(d["clock"], []).append(d)
    return list(groups.items())


def days_label(days: list[dict], prose: bool = False) -> str:
    """'Day 1', 'Days 2–5' (or 'Days 2 to 5' in a sentence)."""
    if len(days) == 1:
        return f"Day {days[0]['n']}"
    dash = " to " if prose else "–"
    return f"Days {days[0]['n']}{dash}{days[-1]['n']}"


ORDINALS = ["first", "second", "third", "fourth", "fifth", "sixth"]


def shape_prose(s: dict) -> str:
    """'45 minutes of briefing, then 50 of lab' (a debrief reads 'a 10-minute debrief')."""
    parts = []
    for i, (part, minutes) in enumerate(s.items()):
        if part == "debrief":
            parts.append(f"a {minutes}-minute debrief")
        else:
            parts.append(f"{minutes} minutes of {part}" if i == 0 else f"{minutes} of {part}")
    return ", ".join(parts[:-1]) + ", then " + parts[-1]


def split_sentences(v: dict, clk: dict, days: list[dict]) -> list[str]:
    """One sentence per unit that a break splits: between a module's briefing and its lab,
    or across a hands-on unit (the capstone) that has neither."""
    out = []
    slots = clk["slots"]
    for i, unit in enumerate(units(clk)):
        if len(unit) < 2:
            continue
        between = slots[slots.index(unit[0]) + 1 : slots.index(unit[1])]
        label = " and ".join(s["label"].lower() for s in between)
        placed = [(d, placements(v, d)[i]) for d in days]
        taught = [d for d, p in placed if shape(v, p["key"])]
        hands_on = [(d, p) for d, p in placed if not shape(v, p["key"])]
        if taught:
            who = "those days" if len(taught) == len(days) else days_label(taught, prose=True)
            out.append(
                f"On {who} the {ORDINALS[i]} module breaks for {label}"
                " between its briefing and its lab."
            )
        for d, p in hands_on:
            title = p["label"] or v["modules"][p["key"]]["title"]
            out.append(
                f"On Day {d['n']}, the {title.lower().replace(': ', ' ')} runs on across {label}."
            )
    return out


def module_shape(v: dict) -> str:
    """How long a module is on each clock, as one short paragraph."""
    sentences = []
    for name, days in clock_groups(v):
        s = v["schedule"]["clocks"][name]["shape"]
        sentences.append(
            f"On {days_label(days, prose=True)}, each module is {sum(s.values())} minutes:"
            f" {shape_prose(s)}."
        )
        sentences += split_sentences(v, v["schedule"]["clocks"][name], days)
    for key, m in modules_in_order(v):
        found = module_placements(v, key)
        if len(found) > 1:
            day_numbers = sorted({d["n"] for d, _ in found})
            where = " and ".join(f"Day {n}" for n in day_numbers)
            sentences.append(
                f"The {m['title'].lower()} (Module {m['n']}) has no briefing: it takes"
                f" {prose_times(module_clock(v, key))} on {where}."
            )
    return " ".join(sentences)


def prose_times(ranges: str) -> str:
    """'11:30–12:25 · 13:25–14:30 · 14:45–16:45' as '11:30–12:25, 13:25–14:30 and 14:45–16:45'."""
    parts = ranges.split(" · ")
    return parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + " and " + parts[-1]


def minute_range(values: list[int]) -> str:
    lo, hi = min(values), max(values)
    return str(lo) if lo == hi else f"{lo}–{hi}"


def exercise_count(v: dict) -> int:
    """Every numbered exercise in every lab, counted from the notebooks themselves."""
    return sum(
        len([r for r in lab_steps.rows(m["slug"]) if r["label"].startswith("Exercise")])
        for _, m in modules_in_order(v)
        if has_notebook(m)
    )


def facts_strip(v: dict) -> str:
    w = v["workshop"]
    taught = [m for m in v["modules"].values() if not is_prework(m)]
    labs = sum(1 for m in v["modules"].values() if has_notebook(m)) + 1  # plus 00-setup
    shapes = [v["schedule"]["clocks"][name]["shape"] for name, _ in clock_groups(v)]
    facts = [
        f"**{w['days']}** days",
        f"**{len(taught)}** modules",
        f"**{labs}** Colab notebooks",
        f"**{exercise_count(v)}** hands-on exercises",
        f"**{minute_range([s['briefing'] for s in shapes])}** min briefings,"
        f" **{minute_range([s['lab'] for s in shapes])}** min labs",
    ]
    debriefs = [s["debrief"] for s in shapes if s.get("debrief")]
    if debriefs:
        facts.append(f"**{minute_range(debriefs)}** min lab debriefs")
    return "::: {.facts}\n" + "\n".join(f"[{f}]{{.fact}}" for f in facts) + "\n:::"


def days_cards(v: dict) -> str:
    out = ["::: {.day-grid}"]
    for d in days_in_order(v):
        taught = [m["n"] for _, m in day_modules(v, d)]
        span_text = f"Modules {taught[0]}–{taught[-1]}"
        out += [
            "::: {.day-card}",
            f"[Day {d['n']}]{{.eyebrow}}",
            "",
            f"[{d['title']}](day-{d['n']}.qmd){{.day-card-title}}",
            "",
            f"[{d['question']}]{{.day-card-question}}",
            "",
            f"[{span_text}]{{.day-card-span}}",
            ":::",
        ]
    out.append(":::")
    return "\n".join(out)


def path_steps(v: dict) -> str:
    """The module arc for the landing page: pre-work, then one step per module by day."""
    groups = []
    if prework(v):
        groups.append((f"[{PREWORK}](setup.qmd#module-0){{.path-day-label}}", prework(v), True))
    for d in days_in_order(v):
        label = f"[Day {d['n']} · {d['short']}](day-{d['n']}.qmd){{.path-day-label}}"
        groups.append((label, day_modules(v, d), False))
    out = ["::: {.path}"]
    for label, mods, optional in groups:
        out += ["::: {.path-day}", label, ""]
        for _, m in mods:
            tag = " [Optional pre-work]{.chip}" if optional else ""
            out += [
                "::: {.path-step" + (" .path-step-optional" if optional else "") + "}",
                f"[{m['n']}]{{.path-num}}",
                "",
                "::: {.path-body}",
                f"[{m['title']}](modules/{m['slug']}.qmd){{.path-title}}{tag}",
                "",
                m["summary"],
                ":::",
                ":::",
            ]
        out.append(":::")
    out.append(":::")
    return "\n".join(out)


def segments(s: dict, slot: dict) -> list[tuple[str, str, int]]:
    """(part, start time, minutes) for the parts of shape `s` that fall in this slot:
    all of them, or the briefing alone (`part: briefing`), or the rest (`part: lab`)."""
    parts = list(s.items())
    if slot.get("part") == "briefing":
        parts = parts[:1]
    elif slot.get("part") == "lab":
        parts = parts[1:]
    t, out = to_minutes(slot["start"]), []
    for part, minutes in parts:
        out.append((part, clock(t), minutes))
        t += minutes
    return out


def bar(segs: list[tuple[str, str, int]]) -> str:
    """The bar under a module: one span per part, each as wide as its minutes."""
    out = []
    for part, start, minutes in segs:
        text = f"{part.capitalize()} {start}"
        grow = f'style="flex-grow: {minutes}"'
        if part == "debrief":
            # Too narrow for its label: the text is for screen readers and the tooltip.
            out.append(f'[[{text}]{{.visually-hidden}}]{{.slot-debrief {grow} title="{text}"}}')
        else:
            out.append(f"[{text}]{{.slot-{part} {grow}}}")
    return "[" + "".join(out) + "]{.slot-split}"


def module_cell(v: dict, p: dict, slot: dict) -> str:
    m = v["modules"][p["key"]]
    cell = f"[{m['n']} · {p['label'] or m['title']}](modules/{m['slug']}.qmd){{.slot-module}}"
    s = shape(v, p["key"])
    hands_on = "[[Hands-on]{.slot-lab}]{.slot-split}"  # the capstone: no briefing/lab split
    return f"{cell} {bar(segments(s, slot)) if s else hands_on}"


def schedule_grid(v: dict, name: str, days: list[dict]) -> str:
    """One timetable for days that share a clock. A plain pipe table: spans carry the
    classes custom.scss uses to tell briefing, lab, debrief, break and clinic apart."""
    clk = v["schedule"]["clocks"][name]
    head = "| Time | " + " | ".join(f"[Day {d['n']}](day-{d['n']}.qmd) {d['short']}" for d in days)
    rows = [head + " |", "|---|" + "---|" * len(days)]
    # Each day's placement for each of the clock's module slots, in clock order.
    owner = {d["n"]: [p for p in placements(v, d) for _ in p["slots"]] for d in days}
    i = 0
    for slot in clk["slots"]:
        cells = []
        for d in days:
            kind = slot["kind"]
            if kind in ("opening", "closing"):
                page = d.get(f"{kind}_page")
                target = f"({page})" if page else ""
                cells.append(f"[{d[kind]}]{target}{{.slot-{kind}}}")
            elif kind == "clinic":
                if d.get("clinic"):
                    key, label = slot_parts(d["clinic"])
                    m = v["modules"][key]
                    link = f"modules/{m['slug']}.qmd"
                    cells.append(f"[{label or m['title']}]({link}){{.slot-clinic}}")
                else:
                    cells.append("")
            elif kind == "break":
                cells.append(f"[{slot['label']}]{{.slot-break}}")
            else:
                cells.append(module_cell(v, owner[d["n"]][i], slot))
        if slot["kind"] == "module":
            i += 1
        rows.append(f"| {slot['start']}–{slot['end']} | " + " | ".join(cells) + " |")
    return "\n".join(rows)


def schedule(v: dict) -> str:
    """The timetable: one grid for each run of days on the same clock."""
    out = []
    for name, days in clock_groups(v):
        minutes = sum(v["schedule"]["clocks"][name]["shape"].values())
        out += [
            f"## {days_label(days)} · {minutes}-Minute Modules {{#clock-{name}}}",
            "",
            f"::: {{.table-wide .timetable .days-{len(days)}}}",
            schedule_grid(v, name, days),
            ":::",
            "",
        ]
    return "\n".join(out)


def welcome_days(v: dict) -> str:
    """The welcome deck's "five days" slide: one row per day with its modules."""
    rows = ["| Day | Theme | Modules |", "|---|---|---|"]
    for d in days_in_order(v):
        mods = ", ".join(f"{m['n']} {m['title']}" for _, m in day_modules(v, d))
        rows.append(f"| [Day {d['n']}](day-{d['n']}.qmd) | {d['title']} | {mods} |")
    return "\n".join(rows)


def modules_text(numbers: list[int]) -> str:
    """'Modules 1, 2, 6 and 11'; a single module reads 'Module 7'."""
    if len(numbers) == 1:
        return f"Module {numbers[0]}"
    return "Modules " + ", ".join(str(n) for n in numbers[:-1]) + f" and {numbers[-1]}"


def welcome_data(v: dict) -> str:
    """The welcome deck's datasets slide: the data that comes back all week. A dataset
    used in two or more modules, in order of first use; pre-work data and the artifacts
    one lab builds for the next (keys labNN_*) are left out."""
    used = [
        d
        for key, d in v["datasets"].items()
        if isinstance(d, dict)
        and len(d.get("modules", [])) > 1
        and min(d["modules"]) > 0
        and not key.startswith("lab")
    ]
    rows = ["| Data | Used in |", "|---|---|"]
    for d in sorted(used, key=lambda d: d["modules"][0]):
        rows.append(f"| {d['name']} | {modules_text(sorted(d['modules']))} |")
    return "\n".join(rows)


def shared_label(pairs: list[tuple[dict, str]]) -> str:
    """One label for days that share a slot: the commonest, with the exceptions named."""
    counts = Counter(label for _, label in pairs)
    main = counts.most_common(1)[0][0]
    others = [f"Day {d['n']}: {label}" for d, label in pairs if label != main]
    return main + (f" ({'; '.join(others)})" if others else "")


def welcome_clocks(v: dict) -> str:
    """The welcome deck's timetable slide: one compact column per clock. Days on one
    clock share a column; a row names the module only when the clock is one day's."""
    groups = clock_groups(v)
    width = f"{98 // len(groups)}%"
    out = ["::: {.columns}"]
    for name, days in groups:
        clk = v["schedule"]["clocks"][name]
        minutes = sum(clk["shape"].values())
        out += [
            f'::: {{.column width="{width}"}}',
            f"**{days_label(days)}** · {minutes}-minute modules",
            "",
            "| Time | |",
            "|---|---|",
        ]
        owner = {d["n"]: [p for p in placements(v, d) for _ in p["slots"]] for d in days}
        i = 0
        for slot in clk["slots"]:
            kind = slot["kind"]
            if kind in ("opening", "closing"):
                text = shared_label([(d, d[kind]) for d in days])
            elif kind == "clinic":
                pairs = []
                for d in days:
                    if d.get("clinic"):
                        key, label = slot_parts(d["clinic"])
                        pairs.append((d, label or v["modules"][key]["title"]))
                text = shared_label(pairs) if pairs else ""
            elif kind == "break":
                text = slot["label"]
            else:
                parts = " · ".join(
                    f"{part.capitalize()} {mins}" for part, _, mins in segments(clk["shape"], slot)
                )
                if len(days) == 1:
                    p = owner[days[0]["n"]][i]
                    m = v["modules"][p["key"]]
                    text = f"{m['n']} · {p['label'] or m['title']}: {parts.lower()}"
                else:
                    hands_on = [d for d in days if not shape(v, owner[d["n"]][i]["key"])]
                    text = parts + "".join(f" (Day {d['n']}: hands-on)" for d in hands_on)
                i += 1
            out.append(f"| {slot['start']}–{slot['end']} | {text} |")
        out += [":::"]
    out.append(":::")
    return "\n".join(out)


def card(v: dict, key: str, m: dict, eyebrow: str, optional: bool = False) -> list[str]:
    """One module card: its clock time (a line per stretch), title, summary, actions."""
    return [
        "::: {.module-card" + (" .module-card-optional" if optional else "") + "}",
        "::: {.module-card-time}",
        module_clock(v, key).replace(" · ", "\\\n"),
        ":::",
        "",
        "::: {.module-card-body}",
        f"[{eyebrow}]{{.eyebrow}}",
        "",
        f"[{m['title']}](modules/{m['slug']}.qmd){{.module-card-title}}",
        "",
        m["summary"],
        "",
        "::: {.module-card-actions}",
        f"[Open the briefing](modules/{m['slug']}.qmd){{.btn-quiet}} {colab_button(v, m)} "
        + chips(m["stack"]),
        ":::",
        ":::",
        ":::",
    ]


def day_cards(v: dict, day: dict) -> str:
    """One card per module of the day, with its clock time; the clinic first, if any."""
    out = ["::: {.module-cards}"]
    if day.get("clinic"):
        key, _ = slot_parts(day["clinic"])
        m = v["modules"][key]
        out += card(v, key, m, f"Module {m['n']} · pre-work, optional clinic", optional=True)
    for key, m in day_modules(v, day):
        out += card(v, key, m, f"Module {m['n']}")
    out.append(":::")
    return "\n".join(out)


# What a participant without keys gets, in a few words, per readiness fallback kind.
FALLBACK_SHORT = {
    "none": "the lab always runs its real models",
    "open-model": "an open model runs in place of the commercial one",
    "toy": "a toy model stands in for the real system; its numbers only illustrate",
}


def part_times(v: dict, key: str) -> str | None:
    """'11:30 briefing · 13:25 lab · 14:20 debrief'; None for a module without a
    briefing/lab shape (pre-work, and the capstone, which is hands-on throughout)."""
    s = shape(v, key)
    found = module_placements(v, key)
    if not s or len(found) != 1:
        return None
    parts = [seg for slot in found[0][1]["slots"] for seg in segments(s, slot)]
    return " · ".join(f"{start} {part}" for part, start, _ in parts)


def run_sheet(v: dict, day: dict) -> str:
    """The day at a glance for the room: for each module its times, what the briefing
    holds, the lab, and what to do when something goes wrong."""
    envs = v["readiness"]["envs"]
    out = ["::: {.run-sheet}"]
    for key, m in day_modules(v, day):
        briefing = live_plan.read(m["slug"])
        link = f"[{m['title']}](modules/{m['slug']}.qmd)"
        title = f"**{module_clock(v, key)} · Module {m['n']} · {link}**"
        parts = part_times(v, key)
        # A module without a briefing/lab shape (the capstone) has no parts to list.
        out += [title + "\\", parts, ""] if parts else [title, ""]
        if briefing["front"].get("live"):
            exposition, activities = live_plan.totals(live_plan.rows(m["slug"], briefing))
            out.append(
                f"- **In the room:** the [live plan](modules/{m['slug']}.qmd#live-plan),"
                f" {exposition} minutes of exposition and {activities} of checks, demos and"
                " predictions."
            )
        else:
            out.append(
                f"- **In the room:** hands-on, in pairs ([the plan](modules/{m['slug']}.qmd))."
            )
        r = m.get("readiness", {})
        if has_notebook(m) and notebook_exists(m["slug"]):
            out += [
                f"- **Lab:** [open in Colab]({v['repo']['colab_base']}/{m['slug']}.ipynb),"
                " a checkpoint after each exercise; about"
                f" {r['estimate_minutes']} minutes of compute ({envs[r['runtime']]['name']},"
                " planned).",
                "- **When something goes wrong:** stuck on exercise N, run its folded"
                " Solution cell, then `workshop.use_reference(N)`, and go on. Without keys, "
                + FALLBACK_SHORT[r["fallback"]["kind"]]
                + ".",
            ]
        out.append("")
    out += [
        ":::",
        "",
        "Compute times are planning estimates, not measurements on the teaching runtime;"
        " the [readiness page](readiness.qmd) has what has been run, where.",
    ]
    return "\n".join(out)


# ---- the module page's details panel, prerequisites and lab task list ----

# What a participant needs in place before the module, per readiness runtime.
RUNTIME_PREREQ = {
    "colab-t4": "A Google account, and the Colab runtime set to **T4 GPU**"
    " (Runtime → Change runtime type).",
    "colab-cpu": "A Google account. Colab's default CPU runtime is enough.",
    "own-laptop": "Your own laptop, set up as on the [Before Day 1](/prepare.qmd) page.",
}
# What the lab does for a participant with no API keys, per readiness fallback.
KEYS_PREREQ = {
    "none": "No API keys: the lab runs its own models throughout.",
    "open-model": "API keys are optional. Without them an open model runs in place of the"
    " commercial one.",
    "toy": "API keys are optional. Without them a toy model stands in, and its numbers only"
    " illustrate.",
}


def module_details(v: dict, key: str, m: dict) -> list[str]:
    """The details panel: duration, level, runtime, cost, accounts. A definition list, so
    each term stays beside its value at any width."""
    r = m.get("readiness", {})
    rows = [
        ("Duration", timing(v, key, m)),
        ("Level", f"{m['level']} · {v['levels'][m['level']]}"),
    ]
    if has_notebook(m):
        env = v["readiness"]["envs"][r["runtime"]]["name"]
        rows.append(("Lab runtime", f"{env} · about {r['estimate_minutes']} minutes of compute"))
    rows.append(("Accounts and cost", _accounts(r)))
    if has_notebook(m):
        rows.append(("Without API keys", FALLBACK_SHORT[r["fallback"]["kind"]]))
    out = ["::: {.module-details}"]
    for term, value in rows:
        out += [term, f":   {value}", ""]
    out[-1] = ":::"
    return out


def prerequisites(v: dict, m: dict) -> list[str]:
    """'Before You Start': the module before this one, the runtime, and the keys."""
    r = m.get("readiness", {})
    items = []
    if not is_prework(m):
        earlier = [x for _, x in modules_in_order(v) if 0 < x["n"] < m["n"]]
        if not earlier:
            setup = v["setup"]
            items.append(
                f"[{setup['title']}](/setup.qmd): the {setup['minutes']}-minute notebook"
                " that checks your Colab runtime and loads any keys."
            )
        else:
            last = earlier[-1]
            link = f"[Module {last['n']} · {last['title']}](/modules/{last['slug']}.qmd)"
            tail = (
                " and its lab."
                if len(earlier) == 1
                else " and its lab, and the modules before it: this module measures its"
                " results against theirs."
            )
            items.append(link + tail)
    items.append(RUNTIME_PREREQ[r["runtime"]])
    if has_notebook(m):
        items.append(KEYS_PREREQ[r["fallback"]["kind"]])
    return ["::: {.prerequisites}", "## Before You Start", ""] + [f"- {i}" for i in items] + [":::"]


def module_block(v: dict, key: str, m: dict) -> str:
    """The header of a module page. Links are project-absolute: the including page
    sits in modules/."""
    if is_prework(m):
        where = f"[{PREWORK}](/setup.qmd#module-0){{.module-day}}"
    else:
        day = next(d for d in v["days"].values() if d["n"] == m["day"])
        where = f"[Day {m['day']} · {day['short']}](/day-{m['day']}.qmd){{.module-day}}"
    # When each part runs; the capstone, with no parts, gives its clock ranges.
    parts = None if is_prework(m) else part_times(v, key) or module_clock(v, key)
    when = f" [{parts}]{{.module-clock}}" if parts else ""
    lines = [
        "::: {.module-header}",
        "::: {.module-meta}",
        f"{where} [Module {m['n']}]{{.module-num}} [{timing(v, key, m)}]{{.module-time}}{when}",
        ":::",
        "",
        "::: {.module-summary}",
        m["summary"],
        ":::",
        "",
        "::: {.module-actions}",
        f"{colab_button(v, m, 'Open the lab in Colab')} {chips(m['stack'])}",
        ":::",
        ":::",
        "",
    ]
    lines += module_details(v, key, m)
    lines += [
        "",
        "::: {.module-outcomes}",
        "## What You Will Build",
        "",
        "In this module you will:",
        "",
    ]
    lines += [f"- {o}" for o in m["objectives"]]
    terms = learner_pages.terms_of(key)
    if terms:
        links = ", ".join(
            f"[{learner_pages.mid_sentence(t['term'])}](/glossary.qmd#{t['id']})" for t in terms
        )
        lines += ["", f"New terms, in the [glossary](/glossary.qmd): {links}."]
    lines += [":::", ""]
    lines += prerequisites(v, m)
    return "\n".join(lines)


LAB_PENDING = "## In the Lab {#in-the-lab}\n\n[Lab in preparation]{.lab-note}"


def lab_block(v: dict, key: str, m: dict) -> str:
    """'In the lab': the notebook's own parts and exercises, with the link that opens it."""
    found = lab_steps.rows(m["slug"])
    _, parts, minutes = lab_steps.totals(found)
    exercises = len([r for r in found if r["label"].startswith("Exercise")])
    s = shape(v, key)
    # A module with no briefing/lab split (the capstone) is hands-on throughout, so its
    # exercises account for a small part of the time.
    budget = (
        f"the lab slot is {s['lab']} minutes"
        if s
        else f"the rest of the {minutes_of(v, key)} minutes is your own pair work"
    )
    lead = (
        f"{exercises} exercises in {parts} parts. The notebook budgets {minutes} minutes for"
        f" them; {budget}. Each exercise you write is a `# TODO` stub with a folded solution"
        " beneath it and a checkpoint that passes or fails; where people tend to stall, a"
        " folded hint sits above the stub."
    )
    # The briefing sections each exercise uses, from the page's `lab:` map (live_plan.py).
    briefing = None
    if (ROOT / "modules" / f"{m['slug']}.qmd").exists():
        page = live_plan.read(m["slug"])
        if live_plan.lab_map(page):
            briefing = {
                f"Exercise {ex}": ", ".join(
                    f"{n} (Reference)" if page["sections"].get(n, {}).get("reference") else str(n)
                    for n in ns
                )
                for ex, ns in live_plan.lab_map(page).items()
            }
    out = [
        "## In the Lab {#in-the-lab}",
        "",
        colab_button(v, m, "Open the lab in Colab"),
        "",
        lead,
        "",
        "::: {.lab-steps}",
        lab_steps.table(found, briefing),
        ":::",
    ]
    found_challenge = lab_steps.challenge(found)
    if found_challenge:
        out += ["", found_challenge]
    if m.get("readiness", {}).get("runtime", "").startswith("colab"):
        out += [
            "",
            "**When you are done.** Runtime \u2192 Disconnect and delete runtime releases the"
            " machine; your keys stay in Colab Secrets for the next lab.",
        ]
    return "\n".join(out)


def notebooks_index(v: dict) -> str:
    s = v["setup"]
    out = [
        "::: {.module-cards}",
        "::: {.module-card}",
        "::: {.module-card-time}",
        "Before Day 1",
        ":::",
        "",
        "::: {.module-card-body}",
        f"[Start here · {s['minutes']} minutes]{{.eyebrow}}",
        "",
        f"[{s['title']}]{{.module-card-title}}",
        "",
        s["summary"],
        "",
        "::: {.module-card-actions}",
        colab_button(v, {"slug": s["slug"]}),
        ":::",
        ":::",
        ":::",
        ":::",
    ]
    for d in days_in_order(v):
        labs = [m for _, m in day_modules(v, d) if has_notebook(m)]
        out += [
            "",
            f"## Day {d['n']} · {d['short']} {{#day-{d['n']}}}",
            "",
            "::: {.notebook-table}",
            "| # | Notebook | Briefing | Lab |",
            "|---|---|---|---|",
        ]
        for m in labs:
            out.append(
                f"| {m['n']} | **{m['title']}** [{m['summary']}]{{.notebook-summary}} "
                f"| [Read](modules/{m['slug']}.qmd) | {colab_button(v, m)} |"
            )
        out.append(":::")
    return "\n".join(out)


def sidebar_yaml(v: dict) -> str:
    """website.sidebar for _quarto.yml (read through metadata-files): the modules
    grouped by day, pre-work first. Quarto shows it on the pages it lists and derives
    the previous/next links at the foot of each briefing from the same order."""
    groups = [(PREWORK, prework(v))] if prework(v) else []
    groups += [(f"Day {d['n']} · {d['short']}", day_modules(v, d)) for d in days_in_order(v)]
    sections = [
        {
            "section": title,
            "contents": [
                {"href": f"modules/{m['slug']}.qmd", "text": f"{m['n']} · {m['title']}"}
                for _, m in mods
            ],
        }
        for title, mods in groups
    ]
    sidebar = {"id": "modules", "title": "Modules", "style": "floating", "contents": sections}
    return yaml.safe_dump(
        {"website": {"sidebar": [sidebar]}}, sort_keys=False, allow_unicode=True, width=1000
    )


def readiness_status(report: dict) -> str:
    """One paragraph: is the workshop ready to teach, and what has run where."""
    s = report["summary"]
    verdict = "ready to teach" if s["ready"] else "not yet ready to teach"
    when = f"As of {s['as_of']}" if s["as_of"] else "No runs are recorded yet"
    parts = [
        f"**{when}: {verdict}.**",
        f"{s['teaching']} of {s['labs']} labs have run end to end, with their current code,"
        " on the Colab runtime they are designed for.",
        f"{s['real']} have run end to end on their real path elsewhere, on another machine"
        " or on the CI runner"
        + (f" ({s['real_quick']} of them only with QUICK settings)" if s["real_quick"] else "")
        + f", and {s['real_partial_only']} more in part.",
    ]
    if s["ci_to"]:
        span = s["ci_to"] if s["ci_from"] == s["ci_to"] else f"{s['ci_from']} to {s['ci_to']}"
        failed = f", {s['ci_failed']} failed" if s["ci_failed"] else ""
        if s["ci_stale"]:
            failed += f", {s['ci_stale']} last ran before their code changed"
        parts.append(
            f"On the GitHub CPU runner (newest run of each notebook, {span}),"
            f" {s['ci_passed']} of {s['notebooks']} notebooks passed{failed};"
            f" {s['ci_doubles']} of the passing runs used test doubles, which check that the"
            " code runs, not what the models do."
        )
    parts.append(f"{s['items_open']} of {s['items']} pieces of blocking work are open.")
    return " ".join(parts)


def readiness_summary(report: dict) -> str:
    return readiness_status(report) + " [What has run, where, and what is missing](/readiness.qmd)."


def _accounts(r: dict) -> str:
    text = ", ".join(r["accounts"])
    if r.get("optional_accounts"):
        text += f"; optional: {', '.join(r['optional_accounts'])}"
    if r["cost"] == "free":
        return f"{text}. Free"
    return f"{text}. {r['cost'][0].upper()}{r['cost'][1:]}"


def _evidence_cell(v: dict, e: dict) -> str:
    def show(r):
        return readiness.describe(v, r) if r is not None else "not run"

    ci = e["ci"]
    if ci is None:
        ci_text = "—"
    elif ci["path"] == "offline":
        ci_text = show(ci) + ", with test doubles"
    else:
        ci_text = show(ci) + ", real path (no test doubles)"
    return "<br>".join(
        [
            "**On its Colab runtime:** " + show(e["teaching"]),
            "**Real path, other runs:** " + show(e["other"]),
            "**CI:** " + ci_text,
        ]
    )


def readiness_table(v: dict, report: dict) -> str:
    """The full readiness page: one row per module, the open work, and a legend."""
    R = v["readiness"]
    envs = R["envs"]
    rows = [
        "| Module | Content | Designed for | Evidence | Without API keys | Accounts and cost |",
        "|---|---|---|---|---|---|",
    ]
    for _, m in modules_in_order(v):
        r = m["readiness"]
        content = f"Briefing {r['briefing']}" + (f" · lab {r['lab']}" if r["lab"] != "none" else "")
        planned = f"{envs[r['runtime']]['name']} · estimate {r['estimate_minutes']} min"
        if has_notebook(m):
            evidence = _evidence_cell(v, report["evidence"][m["slug"]])
        else:
            evidence = "No notebook. Not yet run on a fresh laptop"
        fallback = readiness.FALLBACK_LABELS[r["fallback"]["kind"]]
        rows.append(
            f"| [{m['n']} · {m['title']}](/modules/{m['slug']}.qmd) | {content} | {planned} "
            f"| {evidence} | **{fallback}.** {r['fallback']['note']} | {_accounts(r)} |"
        )
    out = [
        readiness_status(report),
        "",
        "::: {.column-page .table-wide .readiness-table}",
        "\n".join(rows),
        ":::",
        "",
        "## Blocking Work {#open-work}",
        "",
    ]
    for item in report["items"]:
        mods = ", ".join(str(n) for n in item["modules"])
        word = "module" if len(item["modules"]) == 1 else "modules"
        mark = "Done" if item["closed"] else "Open"
        out.append(f"- **{mark}:** {item['title']} ({word} {mods}; {item['why']})")
    out.append("")

    gaps = [m for _, m in modules_in_order(v) if m["readiness"].get("gaps")]
    if gaps:
        out += ["## Known Gaps by Module {#gaps}", ""]
        out += [f"- **{m['n']} · {m['title']}:** {m['readiness']['gaps']}." for m in gaps]
        out.append("")

    out += [
        "## How to Read This Page {#legend}",
        "",
        "**Evidence.** Each line is the newest run of that kind, from the run records in"
        " [`runs/`]({{< var repo.url >}}/tree/main/runs). A newer failure replaces an older"
        " pass, and on the same day a failure wins. *On its Colab runtime* means a worked run"
        " (solutions bound) of the whole notebook, on the path a participant without keys"
        " takes, with no QUICK shortcuts, on the runtime the module is designed for, recorded"
        " by a tool with the notebook's code hash; it stops counting when the code changes."
        " *Real path, other runs* is the newest other run without test doubles, on any"
        " machine except the CI runner; a laptop's or a CPU runner's time does not predict a"
        " T4's. *CI* is the newest run on the GitHub CPU runner: with test doubles it shows"
        " that the code runs, not what a model does. A run marked *before the notebook last"
        " changed* was made against older code; backfilled runs carry no code hash, so they"
        " cannot be checked. An estimate is a planning figure from the lab's brief, not a"
        " measurement. Dates are shown as recorded; the release check will also require a"
        f" teaching run to be at most {R['max_run_age_days']} days old.",
        "",
        "**Paths.**",
        "",
    ]
    out += [f"- `{k}`: {text}." for k, text in R["paths"].items()]
    out += ["", "**Without API keys.**", ""]
    out += [
        f"- *{readiness.FALLBACK_LABELS[k]}*: {text}." for k, text in R["fallback_kinds"].items()
    ]
    return "\n".join(out)


def readme_status(v: dict, report: dict) -> str:
    site = v["repo"]["site_url"]
    return f"> {readiness_status(report)} See the [readiness page]({site}/readiness.html)."


def readme_table(v: dict) -> str:
    site = v["repo"]["site_url"]
    rows = ["| # | Day | Module | Lab |", "|---|---|---|---|"]
    for _, m in modules_in_order(v):
        day = "Pre-work" if is_prework(m) else m["day"]
        rows.append(
            f"| {m['n']} | {day} | [{m['title']}]({site}/modules/{m['slug']}.html) "
            f"| {lab_cell(v, m)} |"
        )
    return "\n".join(rows)


def readme_days(v: dict) -> str:
    """The days, their themes and modules, and how long a module is."""
    rows = ["| Day | Theme | Modules |", "|---|---|---|"]
    if prework(v):
        numbers = ", ".join(str(m["n"]) for _, m in prework(v))
        rows.append(f"| Before Day 1 | Pre-work (optional) | {numbers} |")
    for d in days_in_order(v):
        n = [m["n"] for _, m in day_modules(v, d)]
        rows.append(f"| {d['n']} | {d['title']} | {n[0]}–{n[-1]} |")
    schedule_link = f"The [schedule]({v['repo']['site_url']}/schedule.html) has the times."
    return "\n".join(rows) + f"\n\n{module_shape(v)} {schedule_link}"


def replace_region(path: Path, name: str, body: str) -> None:
    begin, end = f"<!-- BEGIN {name} -->", f"<!-- END {name} -->"
    text = path.read_text(encoding="utf-8")
    if begin not in text or end not in text:
        raise SystemExit(f"{path.name}: missing {begin} / {end} markers")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    path.write_text(f"{head}{begin}\n{body.rstrip()}\n{end}{tail}", encoding="utf-8")


LECTURE_STUB = """---
title: "{{{{< var modules.{key}.title >}}}}"
---

{{{{< include /_includes/module-{n:02d}.md >}}}}

::: {{.callout-note appearance="simple"}}
This briefing has not been drafted yet.
:::
"""


def scaffold_lectures(v: dict) -> None:
    for key, m in modules_in_order(v):
        page = ROOT / "modules" / f"{m['slug']}.qmd"
        if not page.exists():
            page.parent.mkdir(exist_ok=True)
            page.write_text(LECTURE_STUB.format(key=key, n=m["n"]), encoding="utf-8")


def main() -> None:
    v = load_variables()
    write(INCLUDES / "facts.md", facts_strip(v))
    write(INCLUDES / "days.md", days_cards(v))
    write(INCLUDES / "path.md", path_steps(v))
    write(INCLUDES / "schedule.md", schedule(v))
    write(INCLUDES / "module-shape.md", module_shape(v))
    write(INCLUDES / "welcome-days.md", welcome_days(v))
    write(INCLUDES / "welcome-clocks.md", welcome_clocks(v))
    write(INCLUDES / "welcome-data.md", welcome_data(v))
    for d in days_in_order(v):
        write(INCLUDES / f"day-{d['n']}.md", day_cards(v, d))
        write(INCLUDES / f"run-{d['n']}.md", run_sheet(v, d))
    for key, m in modules_in_order(v):
        write(INCLUDES / f"module-{m['n']:02d}.md", module_block(v, key, m))
        lab = INCLUDES / f"lab-{m['n']:02d}.md"
        if not has_notebook(m):
            # No lab at all (pre-work): the page never includes the file.
            lab.unlink(missing_ok=True)
        elif notebook_exists(m["slug"]) and lab_steps.rows(m["slug"]):
            write(lab, lab_block(v, key, m))
        else:
            write(lab, LAB_PENDING)
        briefing = live_plan.read(m["slug"])
        live, pace = INCLUDES / f"live-{m['n']:02d}.md", INCLUDES / f"pace-{m['n']:02d}.md"
        if briefing["front"].get("live"):
            notice = LIVE_NOTICE.format(slug=m["slug"])
            write(live, live_plan.table(m["slug"], briefing), notice)
            write(pace, live_plan.pace_rows(m["slug"], briefing), notice)
        else:
            # A plan that was removed must not leave its old tables on the page.
            live.unlink(missing_ok=True)
            pace.unlink(missing_ok=True)
    write(INCLUDES / "notebooks.md", notebooks_index(v))
    write(INCLUDES / "glossary.md", learner_pages.glossary(v), GLOSSARY_NOTICE)
    write(INCLUDES / "worksheet.md", learner_pages.worksheet(v), WORKSHEET_NOTICE)
    csv_path = learner_pages.WORKSHEET_CSV
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    csv_path.write_text(learner_pages.worksheet_csv(v), encoding="utf-8")
    records = run_records.load_valid(set(v["readiness"]["envs"]))
    report = readiness.build(v, records)
    write(INCLUDES / "readiness-summary.md", readiness_summary(report))
    write(INCLUDES / "readiness.md", readiness_table(v, report))
    sidebar = INCLUDES / "sidebar.yml"
    sidebar.write_text(f"{YAML_NOTICE}\n{sidebar_yaml(v)}", encoding="utf-8")
    replace_region(ROOT / "README.md", "status", readme_status(v, report))
    replace_region(ROOT / "README.md", "modules", readme_table(v))
    replace_region(ROOT / "README.md", "days", readme_days(v))
    scaffold_lectures(v)


if __name__ == "__main__":
    main()
