"""Normalize every notebook under notebooks/.

For each NN-slug.ipynb that matches an entry in _variables.yml this script:
  - owns the first cell (title, Colab badge, timing, objectives) and the last
    cell (next notebook, site link, license), and rewrites both;
  - owns two code cells from scripts/harness.py: the exercise harness right after the
    header, and the checkpoint summary and run record right before the footer;
  - strips outputs and execution counts;
  - gives every cell a stable id and sets the notebook-level metadata.

Everything else is the author's and is left alone.
Running it twice changes nothing.

Run:  uv run --group site python scripts/gen_notebooks.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import nbformat
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import harness  # noqa: E402
import run_records  # noqa: E402
from gen_tables import timing  # noqa: E402  (one source for "120 minutes (55 briefing, ...)")

ROOT = Path(__file__).resolve().parent.parent
NOTEBOOKS = ROOT / "notebooks"
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"
HEADER_ID, FOOTER_ID = "workshop-header", "workshop-footer"
NOTICE = "<!-- GENERATED by scripts/gen_notebooks.py. Do not edit this cell. -->"


def load_variables() -> dict:
    return yaml.safe_load((ROOT / "_variables.yml").read_text(encoding="utf-8"))


def entries(v: dict) -> list[dict]:
    """The setup notebook followed by the modules that have a lab, in teaching order.

    Modules with `notebook: false` (Module 0) are left out, so 00-setup's footer
    points at the first lab, not at a notebook that does not exist.
    """
    setup = {"n": 0, "day": None, "objectives": [], "stack": [], "key": None, **v["setup"]}
    labs = [{**m, "key": key} for key, m in v["modules"].items() if m.get("notebook", True)]
    return [setup] + sorted(labs, key=lambda m: m["n"])


def header_source(v: dict, e: dict) -> str:
    colab = f"{v['repo']['colab_base']}/{e['slug']}.ipynb"
    when = f"Day {e['day']}" if e["day"] else "Before Day 1"
    length = timing(v, e["key"], e) if e["day"] else f"{e['minutes']} minutes"
    lines = [
        NOTICE,
        f"# {e['n']} · {e['title']}",
        "",
        f"[![Open in Colab]({BADGE})]({colab})",
        "",
        f"**{v['workshop']['title']}** · {when} · {length}",
        "",
        e["summary"],
    ]
    if e["objectives"]:
        lines += ["", "**By the end of this notebook you can:**", ""]
        lines += [f"- {o}" for o in e["objectives"]]
    if e["stack"]:
        lines += ["", f"**Stack:** {', '.join(e['stack'])}"]
    return "\n".join(lines)


def footer_source(v: dict, e: dict, nxt: dict | None) -> str:
    site = v["repo"]["site_url"]
    lines = [NOTICE, "---"]
    if nxt and (NOTEBOOKS / f"{nxt['slug']}.ipynb").exists():
        url = f"{v['repo']['colab_base']}/{nxt['slug']}.ipynb"
        lines.append(f"**Next:** [{nxt['n']} · {nxt['title']}]({url})")
    elif nxt:
        lines.append(f"**Next:** {nxt['n']} · {nxt['title']}")
    else:
        lines.append("**This is the last notebook.**")
    lines += [
        "",
        f"[Workshop site]({site}) · [All notebooks]({site}/notebooks.html) · "
        f"[Source]({v['repo']['url']})",
        "",
        f"{v['workshop']['org']} · text CC BY 4.0, code MIT",
    ]
    return "\n".join(lines)


def generated_cell(cell_id: str, source: str):
    cell = nbformat.v4.new_markdown_cell(source)
    cell["id"] = cell_id
    cell["metadata"] = {"tags": ["generated"]}
    return cell


def generated_code_cell(cell_id: str, source: str, form: bool = False):
    cell = nbformat.v4.new_code_cell(source)
    cell["id"] = cell_id
    cell["metadata"] = {"tags": ["generated"]}
    if form:
        cell["metadata"]["cellView"] = "form"
    return cell


def harness_cell_source(v: dict, e: dict, body: list) -> str:
    """The harness cell for a notebook whose own cells are `body`."""
    fallback = e.get("readiness", {}).get("fallback", {})
    kind = fallback.get("kind", "none")
    # What each path can show, and what runs without keys: one source, _variables.yml. The
    # open path says what this lab runs without keys, which is a Hub model only for some.
    paths = {**v["readiness"]["paths"], "open": v["readiness"]["open_ran"][kind]}
    return harness.harness_source(
        e["slug"],
        run_records.sha_of_cells(body),
        harness.exercises_of(body),
        hints=harness.hints_of(body),
        paths={k: text[0].lower() + text[1:] for k, text in paths.items()},
        fallback_note=fallback.get("note") if kind != "none" else None,
        cpu_only=fallback.get("cpu_only", False),
    )


def normalize(nb, v: dict, e: dict, nxt: dict | None):
    owned = (HEADER_ID, FOOTER_ID, *harness.GENERATED_CODE_IDS)
    body = [c for c in nb.cells if c.get("id") not in owned]
    used = set()
    for i, cell in enumerate(body):
        if not cell.get("id") or cell["id"] in used:
            cell["id"] = f"cell-{i:03d}"
        used.add(cell["id"])
        if cell.cell_type == "code":
            cell["outputs"] = []
            cell["execution_count"] = None
    harness_cell = harness_cell_source(v, e, body)
    nb.cells = [
        generated_cell(HEADER_ID, header_source(v, e)),
        generated_code_cell(harness.HARNESS_ID, harness_cell, form=True),
        *body,
        generated_code_cell(harness.SUMMARY_ID, harness.SUMMARY),
        generated_cell(FOOTER_ID, footer_source(v, e, nxt)),
    ]
    nb.metadata = nbformat.NotebookNode(
        {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        }
    )
    nb.nbformat, nb.nbformat_minor = 4, 5
    return nb


def main() -> None:
    v = load_variables()
    order = entries(v)
    known = {e["slug"] for e in order}
    no_lab = {m["slug"] for m in v["modules"].values() if not m.get("notebook", True)}
    for path in sorted(NOTEBOOKS.glob("*.ipynb")):
        if path.stem in no_lab:
            raise SystemExit(f"{path.name}: this module has `notebook: false` in _variables.yml")
        if path.stem not in known:
            raise SystemExit(f"{path.name}: no entry with this slug in _variables.yml")
    for i, e in enumerate(order):
        path = NOTEBOOKS / f"{e['slug']}.ipynb"
        if not path.exists():
            continue
        nxt = order[i + 1] if i + 1 < len(order) else None
        nb = normalize(nbformat.read(path, as_version=4), v, e, nxt)
        nbformat.validate(nb)
        path.write_text(nbformat.writes(nb) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
