"""The exercise harness that scripts/gen_notebooks.py writes into every notebook.

Two generated code cells:
  workshop-harness  (after the header)  WORKED_EXAMPLE switch and the `workshop` object
  workshop-summary  (before the footer) whose checkpoints passed on whose code, and a
                                        run record to paste into runs/

The harness keeps the folded solutions from replacing a participant's code:
@workshop.solution(N) stores a reference solution and binds it only in worked mode, and
workshop.checkpoint(N) at the top of a checkpoint cell makes the cell report whether it
checked the participant's code or the reference. See CONTRIBUTING.md.
"""

from __future__ import annotations

import ast
import re

# Environment variables that put a lab on its offline test path (publish.yml's notebooks
# job), and the other settings a run record may carry. Nothing else from the environment
# goes into a record: it could hold paths or names.
OFFLINE_FLAGS = (
    "NLP_LLMS_OFFLINE_TINY",
    "NLP_LLMS_STUB",
    "NLP_LLMS_LAB07_OFFLINE",
    "NLP_LLMS_LAB09_OFFLINE",
    "NLP_LLMS_LAB10_OFFLINE",
    "NLP_LLMS_LAB13_OFFLINE",
    "NLP_LLMS_LAB14_OFFLINE",
    "NLP_LLMS_LAB15_OFFLINE",
)
RECORDED_SETTINGS = (*OFFLINE_FLAGS, "NLP_LLMS_QUICK", "HF_HUB_OFFLINE")
# Text a lab prints when it could not load an open model and carried on with a stand-in.
# A run that printed one ran test doubles, whatever its flags (scripts/test_notebooks.py and
# the run record both use this list).
FALLBACK_MARKERS = (
    "Could not load ",  # Labs 8, 11, 13, 14: open chat model, encoder, reranker or NLI model
    "did not load",  # Labs 13, 14: build_retriever's encoder or cross-encoder
    "USING StubProvider",  # Labs 8, 11, 13, 14: the test double answered instead of a model
    "LSA stand-in fitted",  # Lab 13: TF-IDF + SVD instead of the dense encoder
    "OFFLINE TEST MODE",  # Labs 6, 7, 10: an offline test flag is set
)

HARNESS_ID = "workshop-harness"
SUMMARY_ID = "workshop-summary"
# Generated code cells: they are not the lab's code, so run_records.content_sha skips them.
GENERATED_CODE_IDS = (HARNESS_ID, SUMMARY_ID)

HARNESS = r'''#@title Workshop harness: run this cell first { display-mode: "form" }
# Generated by scripts/gen_notebooks.py: do not edit this cell.
# Tick WORKED_EXAMPLE to run every reference solution in place of your code. That gives a
# complete worked example; it does not show that you did the exercises.
WORKED_EXAMPLE = False  #@param {type:"boolean"}

import os as _os
import time as _time

from IPython import get_ipython as _get_ipython

_NOTEBOOK = "__NOTEBOOK__"
_CONTENT_SHA = "__CONTENT_SHA__"
_EXERCISES = __EXERCISES__
_HINTS = __HINTS__  # exercises with a folded Hint cell above their TODO cell
_PATHS = __PATHS__
_FALLBACK_NOTE = __FALLBACK_NOTE__
_FALLBACK_CPU_ONLY = __CPU_ONLY__  # the note describes the run a CPU runtime switches to
_RECORDED_SETTINGS = __SETTINGS__
_OFFLINE_FLAGS = __OFFLINE__
_FALLBACK_MARKERS = __MARKERS__
_RECORD_PACKAGES = (
    "torch", "transformers", "numpy", "scikit-learn", "peft", "datasets", "openai",
    "anthropic", "typesafe-sdk", "langgraph", "langchain-core", "llama-index-core",
)


class _Workshop:
    """Keeps the folded solutions from replacing your code, and says whose code each
    checkpoint checked: yours, the reference solution, or code the lab provides."""

    _MISSING = object()

    def __init__(self, old=None):
        # Rerunning this cell (as Run all does) keeps the stored solutions but starts a new
        # run: the checkpoint results, cell times and run clock describe this run only.
        self.ref = getattr(old, "ref", {})
        self.stub = getattr(old, "stub", {})
        self.chosen = getattr(old, "chosen", set())  # exercises switched by use_reference
        self.verified = {}
        self._verifying = None
        self.results = {}
        self.cell_seconds = []
        self.cell_errors = 0
        self.fallbacks = set()
        self.started = _time.time()
        self._current = None
        self._t0 = None

    @property
    def worked(self):
        if _os.environ.get("NLP_LLMS_WORKED") == "1":
            return True
        return bool(_get_ipython().user_ns.get("WORKED_EXAMPLE"))

    def _is_reference(self, n, name, obj):
        return any(obj is r for r in self.ref.get(n, {}).get(name, ()))

    def solution(self, n):
        """Decorator on a reference solution: stores it and, unless WORKED_EXAMPLE is
        ticked, leaves your own definition of the same name in place."""

        def bind(obj, name=None):
            name = name or obj.__name__
            self.ref.setdefault(n, {}).setdefault(name, []).append(obj)
            current = _get_ipython().user_ns.get(name, self._MISSING)
            if current is not self._MISSING and not self._is_reference(n, name, current):
                self.stub.setdefault(n, {})[name] = current
            if self.worked:
                return obj
            if current is not self._MISSING and not self._is_reference(n, name, current):
                self.chosen.discard(n)  # your TODO cell ran again: back to your code
                return current
            if n in self.chosen:
                return obj  # you chose the reference with use_reference(n)
            # Your TODO cell has not run, or the name still holds a reference from a
            # worked run: go back to your code if it is known, never silently to the reference.
            yours = self.stub.get(n, {}).get(name, self._MISSING)
            if yours is not self._MISSING:
                return yours
            if callable(obj):
                return self._not_run(n, name)
            print(f"[workshop] Run your # TODO {n} cell: {name} is the reference until you do.")
            return obj

        return bind

    def _not_run(self, n, name):
        """Stands in for a function or class whose TODO cell has not run yet."""

        def missing(*args, **kwargs):
            raise NotImplementedError(
                f"{name}: run your # TODO {n} cell first, or go on with"
                f" workshop.use_reference({n!r})"
            )

        missing.__name__ = name
        return missing

    def solution_value(self, n, name, value):
        """The same as solution(n), for a value rather than a function or class."""
        if value is None or isinstance(value, (bool, int, float, str, bytes)):
            # Python shares equal small values, so yours and the reference could not be told
            # apart: give such a value in the stub instead of making it part of the exercise.
            kind = type(value).__name__
            raise TypeError(f"solution_value({n!r}, {name!r}): use an object, not a plain {kind}")
        return self.solution(n)(value, name)

    def use_reference(self, n):
        """Go on with the reference solution of exercise n in place of yours."""
        if n not in self.ref:
            raise KeyError(f"Exercise {n} has no reference solution yet: run its Solution cell")
        ns = _get_ipython().user_ns
        for name, objs in self.ref[n].items():
            ns[name] = objs[-1]
        self.chosen.add(n)
        print(
            f"Exercise {n}: now using the REFERENCE solution. Rerun the cells below it."
            f" To switch back to your code, rerun your # TODO {n} cell."
        )

    def checkpoint(self, n=None, label=None):
        """First line of a checkpoint cell: notes whose code the cell is about to check."""
        names = _EXERCISES.get(n, ())
        ns = _get_ipython().user_ns
        k = sum(self._is_reference(n, x, ns.get(x, self._MISSING)) for x in names)
        if not names:
            whose = None  # the results of the cells above: provided code, maybe your earlier work
        elif k == len(names):
            whose = "the REFERENCE solution"
        elif k == 0:
            whose = "your code"
        else:
            whose = "partly the REFERENCE solution"
        self._current = (n, str(label if label is not None else n), whose)

    def _pre(self, info):
        self._t0 = _time.time()

    def _post(self, result):
        if self._t0 is None:  # this harness cell itself: its hooks were registered mid-cell
            return
        self.cell_seconds.append(round(_time.time() - self._t0, 2))
        if not result.success and self._verifying is None:
            self.cell_errors += 1  # a verification copy fails on purpose; it is not an error
        if self._current is None:
            return
        n, label, whose = self._current
        self._current = None
        if self._verifying is not None:
            self.verified[self._verifying] = bool(result.success)
            return
        self.results[label] = (bool(result.success), whose)
        if whose is None:
            if result.success:
                print(f"[workshop] Checkpoint {label} passed.")
            elif isinstance(result.error_in_exec, NotImplementedError):
                print(
                    f"[workshop] Checkpoint {label} uses an exercise you have not written yet."
                    " Finish it, or go on with workshop.use_reference(N) for that exercise."
                )
            else:
                print(f"[workshop] Checkpoint {label} failed. Read the message above.")
        elif result.success:
            print(f"[workshop] Checkpoint {label} passed on {whose}.")
        elif isinstance(result.error_in_exec, NotImplementedError):
            print(
                f"[workshop] Checkpoint {label}: TODO {n} is not written yet. Write it, run"
                " its cell, then rerun this one. To go on without it:"
                f" workshop.use_reference({n!r})"
            )
            if n in _HINTS:
                print(f"[workshop] Stuck? Open the folded Hint above TODO {n} first.")
        elif whose == "the REFERENCE solution":
            print(
                f"[workshop] Checkpoint {label} failed on the reference solution: a problem"
                " with the lab or the runtime, not with your code. Tell the instructor."
            )
        else:
            print(
                f"[workshop] Checkpoint {label} failed on {whose}. Read the assertion above,"
                f" fix TODO {n}, or go on with workshop.use_reference({n!r})."
            )
            if n in _HINTS:
                print(f"[workshop] The folded Hint above TODO {n} says what to check.")

    def _verify_begin(self, n):
        """Test-only (scripts/test_notebooks.py --verify-checkpoints): bind exercise n's
        stubs, so that a copy of its checkpoint runs on unfinished code."""
        ns = _get_ipython().user_ns
        self._saved = {name: ns.get(name, self._MISSING) for name in _EXERCISES.get(n, ())}
        ns.update(self.stub.get(n, {}))
        self._verifying = n

    def _verify_end(self, n):
        """Test-only: restore the reference and require that the stub copy failed."""
        ns = _get_ipython().user_ns
        for name, value in self._saved.items():
            if value is self._MISSING:
                ns.pop(name, None)
            else:
                ns[name] = value
        self._verifying = None
        if self.verified.get(n) is not False:
            raise AssertionError(
                f"The checkpoint of exercise {n} passed on the unfinished stub: it cannot tell"
                " a finished exercise from an unfinished one"
            )

    def summary(self):
        """Which checkpoints passed, and on whose code."""
        groups = {"your code": [], "the reference": [], "other checks": [], "failed": []}
        for label, (ok, whose) in self.results.items():
            if not ok:
                groups["failed"].append(label)
            elif whose is None:
                groups["other checks"].append(label)
            elif whose == "your code":
                groups["your code"].append(label)
            else:
                groups["the reference"].append(label)
        mode = "WORKED EXAMPLE: reference solutions" if self.worked else "your code"
        print(f"{_NOTEBOOK}, run with {mode}.")
        path = self.path()
        # _PATHS comes from readiness.paths in _variables.yml; the offline entry says that
        # such numbers check the code, not a model.
        print(f"  What ran: {_PATHS[path]}.")
        # The labs choose their CPU path from DEVICE; on a GPU a CPU-only note does not apply.
        on_gpu = str(_get_ipython().user_ns.get("DEVICE", "")).startswith("cuda")
        if path == "open" and _FALLBACK_NOTE and not (_FALLBACK_CPU_ONLY and on_gpu):
            print(f"  Read the numbers with this in mind: {_FALLBACK_NOTE}.")
        lines = {
            "your code": "Checkpoints passed on your code",
            "the reference": "Checkpoints passed on a reference solution",
            "other checks": "Other checks passed",
            "failed": "Checkpoints failed",
        }
        for group, labels in groups.items():
            print(f"  {lines[group]}: {', '.join(labels) or 'none'}")
        if self.worked:
            print("  A worked-example run shows how the lab goes, not that you did it.")

    def path(self):
        """offline, keyed or open: the same rule as scripts/add_run_record.py's path_of."""
        ns = _get_ipython().user_ns
        if self.fallbacks or any(_os.environ.get(flag) for flag in _OFFLINE_FLAGS):
            return "offline"
        if ns.get("PROVIDER") in ("openai", "anthropic") or ns.get("JEV_PATH") == "keyed":
            return "keyed"
        return "open"

    def run_record(self):
        """A run record for runs/ (see runs/README.md): paste it into
        scripts/add_run_record.py. It holds no code, outputs, keys or names."""
        import importlib.metadata as _md
        import json
        import platform
        import sys

        gpu = None
        try:
            import torch

            if torch.cuda.is_available():
                gpu = torch.cuda.get_device_name(0)
        except Exception:
            pass
        packages = {}
        for name in _RECORD_PACKAGES:
            try:
                packages[name] = _md.version(name)
            except Exception:
                pass
        import datetime as _dt

        record = {
            "date": _dt.datetime.now(_dt.timezone.utc).date().isoformat(),
            "notebook": _NOTEBOOK,
            "content_sha": _CONTENT_SHA,
            "mode": "worked" if self.worked else "learner",
            # A run passes when it reached this last cell with no error on the way and every
            # checkpoint passed. Run all reruns the harness first, so it starts clean.
            "status": "pass"
            if self.results and self.cell_errors == 0 and all(ok for ok, _ in self.results.values())
            else "fail",
            "cell_errors": self.cell_errors,
            "fallbacks": sorted(self.fallbacks),
            "seconds": round(_time.time() - self.started, 1),
            "cell_seconds": self.cell_seconds,
            "python": platform.python_version(),
            "platform": sys.platform,
            "gpu": gpu,
            "colab_release": _os.environ.get("COLAB_RELEASE_TAG"),
            "provider": _get_ipython().user_ns.get("PROVIDER"),
            "jev_path": _get_ipython().user_ns.get("JEV_PATH"),
            "settings": {k: _os.environ[k] for k in _RECORDED_SETTINGS if _os.environ.get(k)},
            "packages": packages,
        }
        print("----- run record (paste into scripts/add_run_record.py) -----")
        print(json.dumps(record))
        print("----- end of run record -----")


_ip = _get_ipython()
_old = _ip.user_ns.get("workshop")
# Remove only an earlier harness's own hooks; every other hook (Colab's, an extension's)
# stays registered.
for _event in ("pre_run_cell", "post_run_cell"):
    for _callback in list(_ip.events.callbacks[_event]):
        if type(getattr(_callback, "__self__", None)).__name__ == "_Workshop":
            _ip.events.unregister(_event, _callback)
workshop = _Workshop(_old if hasattr(_old, "ref") else None)

# Notice when a lab falls back to a stand-in, for the run record. print is wrapped once.
import builtins as _builtins

if not getattr(_builtins.print, "_workshop", False):
    _print = _builtins.print

    def _watching_print(*args, **kwargs):
        try:
            ip = _get_ipython()
            ws = ip.user_ns.get("workshop") if ip is not None else None
            if ws is not None and hasattr(ws, "fallbacks"):
                # Labs print their fallback notices as strings; never stringify other objects.
                text = " ".join(a for a in args if isinstance(a, str))
                ws.fallbacks.update(m.strip() for m in _FALLBACK_MARKERS if m in text)
        except Exception:
            pass  # watching must never break printing
        return _print(*args, **kwargs)

    _watching_print._workshop = True
    _builtins.print = _watching_print
_ip.events.register("pre_run_cell", workshop._pre)
_ip.events.register("post_run_cell", workshop._post)
print("Workshop harness ready:", "WORKED EXAMPLE" if workshop.worked else "checking your code")
'''

SUMMARY = """# Generated by scripts/gen_notebooks.py: do not edit this cell.
# Which checkpoints passed, and on whose code; then a run record for the instructor.
workshop.summary()
workshop.run_record()"""


def _solution_number(call: ast.Call):
    arg = call.args[0] if call.args else None
    return arg.value if isinstance(arg, ast.Constant) else None


def exercises_of(cells: list) -> dict:
    """{exercise: (names...)} from the @workshop.solution(N) decorators and the
    workshop.solution_value(N, "name", ...) calls in the solution cells."""
    out: dict = {}
    for cell in cells:
        if cell.get("cell_type") != "code" or "solution" not in cell.get("metadata", {}).get(
            "tags", []
        ):
            continue
        source = "".join(cell["source"]) if isinstance(cell["source"], list) else cell["source"]
        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                for dec in node.decorator_list:
                    if (
                        isinstance(dec, ast.Call)
                        and isinstance(dec.func, ast.Attribute)
                        and dec.func.attr == "solution"
                        and isinstance(dec.func.value, ast.Name)
                        and dec.func.value.id == "workshop"
                    ):
                        out.setdefault(_solution_number(dec), []).append(node.name)
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "solution_value"
                and len(node.args) >= 2
                and isinstance(node.args[1], ast.Constant)
            ):
                out.setdefault(_solution_number(node), []).append(node.args[1].value)
    return {n: tuple(names) for n, names in out.items()}


# The summary line of a hint cell: `<summary>Hint for TODO 3</summary>`.
HINT_SUMMARY = re.compile(r"<summary>\s*Hint for TODO (\d+)\s*</summary>")


def hints_of(cells: list) -> list:
    """The exercise numbers that have a hint: a markdown cell tagged `hint`, folded in a
    <details> block whose summary reads "Hint for TODO N"."""
    out = set()
    for cell in cells:
        if cell.get("cell_type") != "markdown" or "hint" not in cell.get("metadata", {}).get(
            "tags", []
        ):
            continue
        source = "".join(cell["source"]) if isinstance(cell["source"], list) else cell["source"]
        if found := HINT_SUMMARY.search(source):
            out.add(int(found.group(1)))
    return sorted(out)


def harness_source(
    slug: str,
    content_sha: str,
    exercises: dict,
    hints: list | None = None,
    paths: dict | None = None,
    fallback_note: str | None = None,
    cpu_only: bool = False,
) -> str:
    return (
        HARNESS.replace("__NOTEBOOK__", slug)
        .replace("__CONTENT_SHA__", content_sha)
        .replace("__EXERCISES__", repr(dict(sorted(exercises.items(), key=lambda kv: str(kv[0])))))
        .replace("__HINTS__", repr(set(hints)) if hints else "set()")
        .replace("__PATHS__", repr(paths or {p: p for p in ("offline", "open", "keyed")}))
        .replace("__FALLBACK_NOTE__", repr(fallback_note))
        .replace("__CPU_ONLY__", repr(bool(cpu_only)))
        .replace("__SETTINGS__", repr(RECORDED_SETTINGS))
        .replace("__OFFLINE__", repr(OFFLINE_FLAGS))
        .replace("__MARKERS__", repr(FALLBACK_MARKERS))
    )
